<?php
module_load_include('inc', 'custom_blocks_base', 'custom_blocks_base.custom_block');
module_load_include('inc', 'custom_blocks_base', 'custom_blocks_base.customblocksmanager');

/**
 * Implements hook_block_info().
 */
function custom_blocks_base_block_info() {
  $block_manager = custom_blocks_base_default_manager();
  return $block_manager->info();
}

/**
 * Implements hook_block_configure().
 */
function custom_blocks_base_block_configure($delta = '') {
  $block_manager = custom_blocks_base_default_manager();
  return $block_manager->configure($delta);
}

/**
 * Implements hook_block_save().
 */
function custom_blocks_base_block_save($delta = '', $edit = array()) {
  $block_manager = custom_blocks_base_default_manager();
  return $block_manager->save($delta, $edit);
}

/**
 * Implements hook_block_view().
 */
function custom_blocks_base_block_view($delta = '') {
  $block_manager = custom_blocks_base_default_manager();
  return $block_manager->view($delta);
}

/**
 * Get all the registered blocks
 */
function custom_blocks_base_registered_blocks() {
  return module_invoke_all('custom_blocks_base_info');
}

/**
 * Get the default Custom Blocks Manager
 */
function custom_blocks_base_default_manager() {
  $manager = &drupal_static(__FUNCTION__);
  if (!$manager) {
    $manager = new CustomBlocksDefaultManager();
  }
  return $manager;
}